language: python
python:
  - 2.7
# This doesn't support 3.3 yet and Pyteomics doesn't support 2.6.
install:
  - sudo apt-get install libxml2-dev libxslt1-dev
  - pip install -r requirements.txt --use-mirrors 
  - pip install -r dev-requirements.txt --use-mirrors
script: nosetests && coverage html
notifications:
  email:
    - jmchilton@gmail.com